### ISSUE TITLE
Results on CIFAR100 and ImageNet

### ISSUE THREAD

**Issue by sooonwoo** [DonkeyShot21/essential-BYOL#1]
Hi, thanks for your impressive work!

I just run your code on CIFAR100 but got 64.22% acc(reported 67%).
Can you let me know what should be the problem?

Also, do you have results on ImageNet?

**Comment by DonkeyShot21** [comment]
This repository is now deprecated in favor of solo-learn (https://github.com/vturrisi/solo-learn).
There we have better results and checkpoints for cifar and imagenet.
